version: '3.8'

services:
  database:
    container_name: database
    image: mysql:latest
    env_file:
      - config/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  server:
    container_name: server
    build:
      context: .
    env_file:
      - config/.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3030:3030"
      - "9229:9229"
    command: npm run start:dev
    depends_on:
      - database
    restart: always

volumes:
  mysql-data:
